i# Change these first
owner: visual-web-design # Your GitHub organization or username, where this repository lives
repo: service-status # The name of this repository

sites:
  - name: 100fitclub
    url: https://100fitclub.com
  - name: amr-classicdrive
    url: https://amr-classicdrive.pt
  - name: amr-imoveis
    url: https://amr-imoveis.pt
  - name: App 100fitclub
    url: https://app.100fitclub.com
  - name: benali
    url: https://benali.org
  - name: prosnowlife
    url: https://prosnowlife.com
  - name: ricardoguiomar
    url: https://ricardoguiomar.pt
  - name: diamondsevents
    url: https://diamondsevents.org
  - name: dlgportas
    url: https://dlgportas.com
  - name: dropandlock
    url: https://dropandlock.pt
  - name: fatorx
    url: https://fatorx.pt
  - name: fatorx
    url: https://formacao.fatorx.pt
  - name: jvparts
    url: https://jvparts.pt
  - name: projetomatic
    url: https://loja.projetomatic.pt
  - name: mafaldagranado
    url: https://mafaldagranado.com
  - name: visualwebdesign
    url: https://my.visualwebdesign.pt
  - name: visualwebdesign
    url: https://new.visualwebdesign.pt
  - name: paivasom
    url: https://paivasom.com
  - name: parquemonteverde
    url: https://parquemonteverde.com
  - name: phunkpt
    url: https://phunk.pt
  - name: projetomatic
    url: https://projetomatic.pt
  - name: prosnowlife
    url: https://prosnowlife.com
  - name: ricardoguiomar
    url: https://ricardoguiomar.pt
  - name: terrierclubedepo
    url: https://terrierclubedeportugal.pt
  - name: ultralogic
    url: https://ultra-logic.pt
  - name: villasjoinal
    url: https://villasjoinal.com
  - name: visualwebdesign
    url: https://visualwebdesign.net
  - name: visualwebdesign
    url: https://visualwebdesign.pt

    sites:
  - name: HTTP
    check: "tcp-ping"
    url: $VWD_SV
    port: 443
  - name: IMAP
    check: "tcp-ping"
    url: $VWD_SV
    port: 993
  - name: POP3
    check: "tcp-ping"
    url: $VWD_SV
    port: 995
  - name: SMTP
    check: "tcp-ping"
    url: $VWD_SV
    port: 465

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /service-status
  logoUrl: https://github.com/visual-web-design/services-status/blob/master/assets/logo_transp.png

  
  name: VWD
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
